
title: Shivani Kumari â€“ Data Analytics Portfolio
name: Shivani Kumari
bio: Aspiring Data Analyst | Excel | SQL | Power BI

email: kumarishivani54653@gmail.com
phone: 9241209387
linkedin: https://www.linkedin.com/in/shivani-kumari-3266a42b8


